name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: 
          - name: Storage - S3 Versioning API
            dir: storage/s3/202507_s3_versioning_an_api_perspective
            cdk: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install CDK
      run: npm install -g aws-cdk
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Configure AWS credentials
      if: matrix.tests.cdk == true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: Install Python CDK dependencies
      if: matrix.tests.cdk == true
      working-directory: ${{ matrix.tests.dir }}/demo/infra
      run: |
        python -m pip install --upgrade pip
        pip install aws-cdk-lib constructs
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    
    - name: CDK Deploy
      if: matrix.tests.cdk == true
      working-directory: ${{ matrix.tests.dir }}/demo/infra
      run: cdk deploy --require-approval never
    
    - name: Install test dependencies
      working-directory: ${{ matrix.tests.dir }}/demo/tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      working-directory: ${{ matrix.tests.dir }}/demo/tests
      continue-on-error: true
      run: |
        pytest --ctrf=ctrf.json
    
    - name: Publish Test Report
      working-directory: ${{ matrix.tests.dir }}/demo/tests
      uses: ctrf-io/github-test-reporter@v1
      with:
        report-path: './ctrf.json'
        github-report: true
      if: always()
      continue-on-error: true
    
    - name: CDK Destroy
      if: matrix.tests.cdk == true && always()
      working-directory: ${{ matrix.tests.dir }}/demo/infra
      run: cdk destroy --force